name: Build repository from PRs
on:
  pull_request:
    branches: [ "master"]

concurrency:
  group: ${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

env:
  BASE_REPO_URL: https://bboozzoo.github.io/snapd-amazon-linux

jobs:
  build-repo:
    strategy:
      fail-fast: false
      matrix:
        target: ["amazonlinux:2", "amazonlinux:2023"]
        include:
          - target: amazonlinux:2
            repo_tarball_name: amazon-linux-2-repo.tar.xz
            artifact_name: repo-tarball-amazonlinux-2
            repo_url_suffix: amzn2
          - target: amazonlinux:2023
            repo_tarball_name: amazon-linux-2023-repo.tar.xz
            artifact_name: repo-tarball-amazonlinux-2023
            repo_url_suffix: al2023

    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build repository artifacts
      id: build-repo
      uses: "./.github/actions/build-repo"
      with:
        target: ${{ matrix.target }}
        repo_tarball_name: ${{ matrix.repo_tarball_name }}
        repo_artifact_name: ${{ matrix.artifact_name }}
        repo_url: ${{ env.BASE_REPO_URL }}/${{ matrix.repo_url_suffix }}
